In [1]:
import pandas as pd

In [4]:
code_data = pd.read_csv("../data/GDP/country_code.csv")
gdp_data = pd.read_csv("../data/GDP/API_NY.GDP.MKTP.KD.ZG_DS2_en_csv_v2_713083.csv", skiprows=[0,1,2,3])

In [8]:
# gdp_data.fillna(0)
code_data

,COUNTRY,COUNTRY CODE,ISO CODES,POPULATION,AREA KM2,GDP $USD
0,Afghanistan,93,AF / AFG,"29,121,286","647,500",20.65 Billion
1,Albania,355,AL / ALB,"2,986,952","28,748",12.8 Billion
2,Algeria,213,DZ / DZA,"34,586,184","2,381,740",215.7 Billion
3,American Samoa,1-684,AS / ASM,"57,881",199,462.2 Million
4,Andorra,376,AD / AND,"84,000",468,4.8 Billion
...,...,...,...,...,...,...
235,Wallis and Futuna,681,WF / WLF,"16,025",274,NaN
236,Western Sahara,212,EH / ESH,"273,008","266,000",NaN
237,Yemen,967,YE / YEM,"23,495,361","527,970",43.89 Billion
238,Zambia,260,ZM / ZMB,"13,460,305","752,614",22.24 Billion
239,Zimbabwe,263,ZW / ZWE,"11,651,858","390,580",10.48 Billion

In [39]:
two_list = []
three_list = []
for d in code_data["ISO CODES"].str.split("/"):
    two_list.append(d[0].strip(" "))
    three_list.append(d[1].strip(" "))

three_dict = {}
for index, name in enumerate(code_data["COUNTRY"]):
    three_dict[three_list[index]] = name
    
# three_dict

In [23]:
gdp_data["Country/Other"] =  [d in three_dict for d in gdp_data["Country Code"]]

In [35]:
country_gdp = gdp_data[gdp_data["Country/Other"]].fillna(0)

In [37]:
country_gdp.to_csv("../data/GDP/country_GDP.csv", index=False)

In [38]:
country_gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64,Country/Other
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.369863,4.198232,0.848228,-0.450586,-0.211225,1.330511,0.000000,0.0,0.0,True
1,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,12.752287,5.600745,2.724543,1.451315,2.260314,2.665292,1.030660,0.0,0.0,True
2,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,8.542147,4.954590,4.822626,0.943576,-2.580097,-0.147207,-2.133493,0.0,0.0,True
3,Albania,ALB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.417524,1.001989,1.774487,2.218751,3.314805,3.821081,4.145238,0.0,0.0,True
4,Andorra,AND,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,-1.615218,0.351645,2.277683,0.842204,1.889124,1.724022,1.629345,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.809626,3.441469,1.222803,4.095281,4.070292,4.226087,3.813314,0.0,0.0,True
260,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.392990,4.823519,-0.188690,-16.678463,-13.621458,-5.942320,-2.701475,0.0,0.0,True
261,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,3.844751,6.177883,7.373613,7.939782,6.122761,...,2.213355,2.485201,1.846992,1.193733,0.399088,1.414513,0.787056,0.0,0.0,True
262,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,1.361382,-2.490839,3.272393,12.214048,16.647456,...,7.597617,5.059376,4.695826,2.919881,3.757178,3.403169,3.794901,0.0,0.0,True
263,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.0,6.316157,1.434471,6.244345,-1.106172,4.910571,...,16.665429,1.989493,2.376929,1.779873,0.755869,4.704035,6.159190,0.0,0.0,True